### ISSUE TITLE
latest macOS_Updater from 5.12.2018 Error URL not found

### ISSUE THREAD

**Issue by FritzHeckert** [Gengik84/MacOS_Updater#1]
Hello Gengik84

You last Version have a Error when will update in a HFS+Partition for Mojave 10.14.2 Bet4 to Final.
"URL not found" is the message.

**Comment by Gengik84** [comment]
Hi.. I don't know your problem but this script is ok.
I used it yesterday and today, I updated several disks.
I tried again now, the result is ok.
![schermata 2018-12-06 alle 18 57 43](https://user-images.githubusercontent.com/14853542/49602472-d806e880-f988-11e8-9a11-b9a3f322fc51.png)

**Comment by FritzHeckert** [comment]
Yes you have option „Normal“ i have Option „beta“  selectet for download i will Developer beta download nit Normal.

Greeting Fritz

Am 06.12.2018 um 18:58 schrieb Gengik84 <notifications@github.com<mailto:notifications@github.com>>:


Hi.. I don't know your problem but this script is ok.
I used it yesterday and today, I updated several records.
I tried again now, the result is ok.
[schermata 2018-12-06 alle 18 57 43]<https://user-images.githubusercontent.com/14853542/49602472-d806e880-f988-11e8-9a11-b9a3f322fc51.png>

**Comment by Gengik84** [comment]
The script is ready to be used in the future 10.14.3 beta 1.
It is still not present.
So it is normal that this channel does not work for the moment.
Please see this line
https://github.com/Gengik84/MacOS_Updater/blob/master/MacOS_Updater#L29
if you want to download the old beta, you must change that line for your personal use.

**Comment by Gengik84** [comment]
Not a script issue.
