### ISSUE TITLE
Downloaded update is corrupted

### ISSUE THREAD

**Issue by STiXzoOR** [Gengik84/MacOS_Updater#2]
**EDIT: managed to fix my issues. check the pull request #3.**

hello, just recently i found this and i went ahead and try it since i'm using mojave on HFS+ so i can update to latest version but i have two problems. 

The first one is that the script tries to create a folder in home directory to store the preference file but it fails because for some reason the `users` invocation has my username twice instead of one (stix stix). I managed to fix that by modifying the script to use the `$HOME` variable instead of the full path. 

The second problem is that when it tried to download the delta update, since i'm on 10.14.2, the update gets corrupted. I checked the script and i found that it tries to download the supplement update instead of the actual update. When executing the `gUrlIndex` variable it returns two downloads, one for the supplement and one for the actual update, but i guess it takes only the first one in account and downloads the wrong one hence the corrupted update. Below is a screenshot of what i'm talking about.

![Screenshot 2019-03-21 at 17 19 27](https://user-images.githubusercontent.com/23358296/54764112-d1cb0e00-4bff-11e9-8e8c-4277ef592e49.png)

Can we implement a function or something to check whether the actual is installed so it an download the supplement one and if not download the actual update, install it and then download the supplement and install it too? Maybe through the build number since it is always different.

**Comment by PMheart** [comment]
Hi,

OK. Finally I have merged your PR and posted one more commit that reverts README, [please take a look](https://github.com/Gengik84/MacOS_Updater/commit/36dd32b307482a5822e4a9a0be8344ce72709291). :)

**Comment by STiXzoOR** [comment]
cool thanks man :-)
