### ISSUE TITLE
macOSUpdCombo10.14.4.RecoveryHDUpdate.pkg NOT found!

### ISSUE THREAD

**Issue by applemanD** [Gengik84/MacOS_Updater#7]
[Terminal Saved Output.pdf](https://github.com/Gengik84/MacOS_Updater/files/3017553/Terminal.Saved.Output.pdf)
file not found, but is in tmp folder ???

**Comment by PMheart** [comment]
Hi,

Looks like Apple is extremely messy with its naming mechanism. https://github.com/Gengik84/MacOS_Updater/commit/46e72d99a1efa95ade2b960829d30b11e39293fa should have fixed your problem and please give it a try.

Thanks.

**Comment by PMheart** [comment]
Hi again,

I am kind of curious about if 1.0.16 fixes the issue, please get the issue updated and close it if it does.

Thanks!

**Comment by applemanD** [comment]
yes.. sorry i got busy.. it did fix the problem
